### ISSUE TITLE
Trouble setting project up 

### ISSUE THREAD

**Issue by isaacjoy** [aws-samples/websocket-chat-application#26] opened 2023-01-30 19:44 UTC
Hi there,

I'm new to AWS in general, but I've followed the deployment instructions and seem to keep running into issues.

1.  When building the frontend I receive these errors after running `ng build --prod`.

<img width="1447" alt="Screenshot 2023-01-30 at 13 39 27" src="https://user-images.githubusercontent.com/22734574/215578615-ce6f82c3-0e53-4ef2-a9f4-898902a0bb82.png">

2. When following the instructions to build infrastructure for TS, I receive this error:

<img width="1792" alt="Screenshot 2023-01-30 at 13 41 45" src="https://user-images.githubusercontent.com/22734574/215579212-0b974df9-713e-4f97-917d-e80060207c11.png">

Please can you explain why I'm receiving these errors.

Thanks,
Isaac

**Comment by santatamas** [comment] 2023-01-31 09:27
Hi Isaac,

The frontend and the backend-ts projects are using shared models for communication. Apparently it can't find those files - although it can be a URL mismatch in the folder structure somewhere. 

I'll have a look (it's due for an Angular version update anyway!), but in the meantime - you don't have to actually compile the frontend. After a clean clone of the repo, you can just deploy the backend, which will deploy a pre-compiled version of the frontend. Your backend fails because your frontend build fails (hence nothing to deploy from the assets).

This week is incredibly busy, but I'll keep you up-to-date on the progress.

Kind regards,
Tamas

**Comment by isaacjoy** [comment] 2023-01-31 17:41
Hey Tamas — thanks for the swift reply.

Yes you're right, the errors seem to be linked.
I only installed Angular yesterday so maybe it's because of a different version. Mine is perhaps too new?
I did do a clean clone of the repo and this is the error I got.

No rush, I appreciate the help
Isaac

**Comment by isaacjoy** [comment] 2023-01-31 17:42
Perhaps this helps

<img width="1447" alt="Screenshot 2023-01-30 at 13 39 27" src="https://user-images.githubusercontent.com/22734574/215840709-b8c5dd1c-37f5-4497-8650-54c567a213d1.png">

**Comment by isaacjoy** [comment] 2023-01-31 17:43
Perhaps this helps

<img width="461" alt="Screenshot 2023-01-31 at 11 42 25" src="https://user-images.githubusercontent.com/22734574/215840794-096af53c-cba0-4b83-b884-676a14986a32.png">

**Comment by santatamas** [comment] 2023-01-31 21:25
You Angular CLI is the latest version, so it should be fine :) But as I said, you don't need to compile the frontend. Just skip that and install the backend if you want to give the example a try (after a clean clone of the repo)! 

I'll probably separate the models to be honest, since the shared approach worked well when I only had a Typescript backend. Now with the NET7 addition I have to have separate model files for both backend and frontend, so it doesn't really make sense to share them anymore. That will most definitely fix the error you're facing now.

I put some time aside this Friday to work on this, I'll keep you in the loop!

Cheers,
Tamas

**Comment by Phil1216** [comment] 2023-02-03 04:01
I had the exact same problem. The issue is that the directory is called infrastructure-ts/resources/models while the import is looking for infrastructure/resources/models. This issue was likely introduced with the .NET infrastructure. Renaming "infrastructure-ts" back to "infrastructure" fixed it for me.

**Comment by santatamas** [comment] 2023-02-03 13:38
Ah that was my mistake, sorry. I'll push a fix today.

**Comment by santatamas** [comment] 2023-02-03 15:26
I have pushed various fixes, which should fix your building issue. Please re-clone the repo, and let me know how it goes :)

**Comment by santatamas** [comment] 2023-02-07 12:26
Closing this issue for the meantime as the issues mentioned should be fixed by the latest updates. Please open a new issue if you're still facing problems!

**Closed by santatamas** 2023-02-07 12:26 UTC
